import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Language = "en" | "yo" | "ha" | "ig" | "pcm";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};

// Cache audio blobs so we don't re-fetch for the same language
const audioCache: Partial<Record<Language, string>> = {};

const speakWelcome = async (language: Language) => {
  try {
    // Use cached URL if available
    if (audioCache[language]) {
      const audio = new Audio(audioCache[language]);
      audio.play();
      return;
    }

    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
    const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    const response = await fetch(`${supabaseUrl}/functions/v1/welcome-tts`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: supabaseKey,
        Authorization: `Bearer ${supabaseKey}`,
      },
      body: JSON.stringify({ language }),
    });

    if (!response.ok) throw new Error("TTS request failed");

    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    audioCache[language] = url;

    const audio = new Audio(url);
    audio.play();
  } catch (err) {
    console.warn("ElevenLabs TTS failed, falling back to browser speech:", err);
    // Fallback to browser speech synthesis
    const fallbackTexts: Record<Language, string> = {
      en: "Welcome to Bailout",
      yo: "E kaabo si Bailout",
      ha: "Barka da zuwa Bailout",
      ig: "Nnọọ na Bailout",
      pcm: "You dey welcome to Bailout",
    };
    if ("speechSynthesis" in window) {
      window.speechSynthesis.cancel();
      const msg = new SpeechSynthesisUtterance(fallbackTexts[language]);
      msg.lang = "en-US";
      window.speechSynthesis.speak(msg);
    }
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>("en");

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    speakWelcome(newLang);
  }, []);

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.about": "About Us",
    "nav.solution": "Solution",
    "nav.features": "Features",
    "nav.team": "Team",
    "nav.help": "Help",
    "nav.getStarted": "Get Started",

    // Hero
    "hero.badge": "Nigeria's MSME Financial Platform",
    "hero.title1": "Connecting MSMEs to",
    "hero.titleHighlight": "Loans, Grants",
    "hero.title2": "& Financial Growth",
    "hero.subtitle": "Transparently connecting businesses to funding opportunities with data-driven insights. Built for Nigeria, designed for growth.",
    "hero.cta1": "Start Your Application",
    "hero.cta2": "Learn More",
    "hero.stat1Value": "₦50B+",
    "hero.stat1Label": "Funding Opportunities",
    "hero.stat2Value": "10K+",
    "hero.stat2Label": "MSMEs Connected",
    "hero.stat3Value": "100+",
    "hero.stat3Label": "Partner Institutions",

    // What We Do
    "whatwedo.tag": "What We Do",
    "whatwedo.title1": "Strengthening MSMEs for",
    "whatwedo.titleHighlight": "Sustainable Growth",
    "whatwedo.subtitle": "At Prime-Up Solutions (Bailout), we strengthen Micro, Small, and Medium Enterprises by improving access to funding, providing expert advisory, and connecting businesses with the right opportunities.",
    "whatwedo.f1Title": "MSME Financing Support",
    "whatwedo.f1Desc": "Connecting businesses with the right funding opportunities tailored to their needs and capacity.",
    "whatwedo.f2Title": "Financial Advisory",
    "whatwedo.f2Desc": "Expert guidance on cash flow management, growth strategies, and operational sustainability.",
    "whatwedo.f3Title": "Growth Acceleration",
    "whatwedo.f3Desc": "Supporting scale and expansion through structured operations and strategic planning.",
    "whatwedo.f4Title": "Innovation & Tools",
    "whatwedo.f4Desc": "Data-driven financial solutions that help businesses make informed decisions.",

    // Problem/Solution
    "ps.problemTag": "The Problem",
    "ps.problemTitle": "Current systems are siloed, opaque, and inefficient",
    "ps.p1": "MSMEs struggle to access credit due to poor visibility into their cashflows",
    "ps.p2": "Lenders lack reliable, real-time risk signals for informal businesses",
    "ps.p3": "Grant opportunities are fragmented and hard to discover",
    "ps.p4": "Policymakers lack granular MSME data for planning",
    "ps.solutionTag": "The Solution",
    "ps.solutionTitle": "Bailout: A two-sided financial marketplace",
    "ps.solutionDesc": 'Powered by a credit intelligence engine, operating as "Banking-in-a-Box" — modular, data-driven, and interoperable.',
    "ps.s1": "Matches borrowers to suitable loan instruments",
    "ps.s2": "Connects grant seekers to relevant opportunities",
    "ps.s3": "Assesses risk using transaction data + manual cash inputs",
    "ps.s4": "Provides anonymized market analytics for institutions",
    "ps.ctaTitle": "Ready to transform your business?",
    "ps.ctaDesc": "Join thousands of MSMEs already using Bailout to access funding.",
    "ps.ctaButton": "Get Started Today",

    // Features
    "features.tag": "Core Features",
    "features.title1": "Everything you need to",
    "features.titleHighlight": "access funding",
    "features.subtitle": "Our comprehensive platform provides all the tools MSMEs need to connect with lenders and access grants efficiently.",
    "features.f1Title": "User Profiles",
    "features.f1Desc": "CAC-linked business profiles with sector details, POS connection, transaction tracking, and credit history.",
    "features.f2Title": "Lender-Borrower Matching",
    "features.f2Desc": "Rules + scoring-based algorithm considering cashflow stability, revenue trends, and sector risk.",
    "features.f3Title": "Grant Discovery Engine",
    "features.f3Desc": "Find relevant grants based on your business profile, sector, and eligibility criteria.",
    "features.f4Title": "Credit Scoring & Risk",
    "features.f4Desc": "Hybrid model using transaction-based metrics and business behavior indicators.",
    "features.f5Title": "Secure Disbursement",
    "features.f5Desc": "Offer acceptance, disbursement tracking, and repayment status monitoring.",
    "features.f6Title": "Market Intelligence",
    "features.f6Desc": "Aggregated insights on sectoral trends, credit demand, and regional indicators.",

    // Value Proposition
    "vp.tag": "Value Propositions",
    "vp.title1": "Benefits for",
    "vp.titleHighlight": "everyone",
    "vp.borrowerTag": "For Borrowers / MSMEs",
    "vp.borrowerTitle": "Unlock your business potential",
    "vp.b1Title": "Unlock Opportunities",
    "vp.b1Desc": "Discover funding and advisory options tailored to your business needs.",
    "vp.b2Title": "Seamless Applications",
    "vp.b2Desc": "Apply easily through our streamlined digital platform.",
    "vp.b3Title": "Real-Time Updates",
    "vp.b3Desc": "Stay informed at every step of your application journey.",
    "vp.lenderTag": "For Lenders / Institutions",
    "vp.lenderTitle": "Make smarter lending decisions",
    "vp.l1Title": "Lower Risk",
    "vp.l1Desc": "Data-driven insights reduce lending risk significantly.",
    "vp.l2Title": "Vetted Pipeline",
    "vp.l2Desc": "Access to pre-screened, qualified MSME borrowers.",
    "vp.l3Title": "Market Intelligence",
    "vp.l3Desc": "Strategic planning with comprehensive market insights.",

    // Mission/Vision
    "mv.missionTitle": "Our Mission",
    "mv.missionDesc": "To simplify access to finance by connecting businesses, lenders, and grant providers on a single transparent platform.",
    "mv.visionTitle": "Our Vision",
    "mv.visionDesc": "To become Africa's most trusted platform for inclusive financial growth and MSME empowerment.",
    "mv.longTermTitle": "Long-term Vision",
    "mv.lt1": "Nigeria's MSME financial operating system",
    "mv.lt2": "Bridge between informal cashflows and formal credit",
    "mv.lt3": "Trusted data layer for inclusive finance",

    // Team
    "team.tag": "Our Team",
    "team.title1": "Meet the",
    "team.titleHighlight": "founding team",
    "team.subtitle": "A dedicated team of professionals committed to transforming MSME access to finance in Nigeria.",
    "team.jmRole": "Founder",
    "team.jmDesc": "Financial services professional with expertise in risk management, strategy, and loan systems.",
    "team.iaRole": "Co-Founder",
    "team.iaDesc": "Brings expertise in strategy, operations, and team-building; drives alignment and organizational growth.",
    "team.soRole": "Strategic Partner & Co-Founder",
    "team.soDesc": "Advisor with strong experience in entrepreneurship support, funding strategies, and SME development.",
    "team.amRole": "Co-Founder",
    "team.amDesc": "Instrumental in shaping the Bailout concept, driving research, strategy, and design execution.",

    // Footer
    "footer.desc": "Connecting MSMEs to loans, grants, and financial institutions transparently, data-driven, Nigeria-focused.",
    "footer.quickLinks": "Quick Links",
    "footer.aboutUs": "About Us",
    "footer.solution": "Solution",
    "footer.features": "Features",
    "footer.ourTeam": "Our Team",
    "footer.forUsers": "For Users",
    "footer.borrowers": "MSMEs / Borrowers",
    "footer.lenders": "Lenders",
    "footer.grantProviders": "Grant Providers",
    "footer.institutions": "Institutions",
    "footer.contactUs": "Contact Us",
    "footer.copyright": "© 2026 Prime-Up Solutions Ltd. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
  },

  yo: {
    "nav.about": "Nípa Wa",
    "nav.solution": "Ojútùú",
    "nav.features": "Àwọn Ẹ̀yà",
    "nav.team": "Ẹgbẹ́",
    "nav.help": "Ìrànlọ́wọ́",
    "nav.getStarted": "Bẹ̀rẹ̀",

    "hero.badge": "Pẹpẹ Ìṣúná MSME ti Nàìjíríà",
    "hero.title1": "Ṣíṣe àjọpọ̀ MSME pẹ̀lú",
    "hero.titleHighlight": "Àwín, Ẹ̀bùn",
    "hero.title2": "& Ìdàgbàsókè Ìṣúná",
    "hero.subtitle": "Ṣíṣe àjọpọ̀ àwọn iṣẹ́ pẹ̀lú àǹfààní ìṣúná lọ́nà títọ́ pẹ̀lú ìmọ̀ tí ó dá lórí dátà. Ti a ṣe fún Nàìjíríà, tí a ṣe fún ìdàgbàsókè.",
    "hero.cta1": "Bẹ̀rẹ̀ Ohun Elo Rẹ",
    "hero.cta2": "Kọ́ Síi",
    "hero.stat1Value": "₦50B+",
    "hero.stat1Label": "Àǹfààní Ìṣúná",
    "hero.stat2Value": "10K+",
    "hero.stat2Label": "Àwọn MSME tí ó Sopọ̀",
    "hero.stat3Value": "100+",
    "hero.stat3Label": "Àwọn Àjọ Alábàáṣiṣẹ́pọ̀",

    "whatwedo.tag": "Ohun Tí A Ń Ṣe",
    "whatwedo.title1": "Mímú MSME Lágbára fún",
    "whatwedo.titleHighlight": "Ìdàgbàsókè Alálòpẹ́",
    "whatwedo.subtitle": "Ní Prime-Up Solutions (Bailout), a ń mú àwọn Iṣẹ́ Kékeré, Àárín àti Àlàárín lágbára nípa mímú ànfààní ìṣúná pọ̀ sí i, pípèsè ìmọ̀ràn ọjọ́gbọ́n, àti ṣíṣe àjọpọ̀ àwọn iṣẹ́ pẹ̀lú àǹfààní tó dára.",
    "whatwedo.f1Title": "Àtìlẹ́yìn Ìṣúná MSME",
    "whatwedo.f1Desc": "Ṣíṣe àjọpọ̀ àwọn iṣẹ́ pẹ̀lú àǹfààní ìṣúná tó bá àìní wọn mu.",
    "whatwedo.f2Title": "Ìmọ̀ràn Ìṣúná",
    "whatwedo.f2Desc": "Ìtọ́sọ́nà ọjọ́gbọ́n lórí ìṣàkóso owó, àwọn ìlànà ìdàgbàsókè, àti ìṣiṣẹ́ alálòpẹ́.",
    "whatwedo.f3Title": "Ìmúyára Ìdàgbàsókè",
    "whatwedo.f3Desc": "Àtìlẹ́yìn fún ìtànkálẹ̀ nípa ìṣiṣẹ́ tó ní ètò àti ìgbèrò ọgbọ́n.",
    "whatwedo.f4Title": "Ìmọ̀-ẹ̀rọ & Irinṣẹ́",
    "whatwedo.f4Desc": "Àwọn ojútùú ìṣúná tí ó dá lórí dátà tí ó ń ràn àwọn iṣẹ́ lọ́wọ́ láti ṣe ìpinnu tó dára.",

    "ps.problemTag": "Ìṣòro Náà",
    "ps.problemTitle": "Àwọn ètò lọ́wọ́lọ́wọ́ jẹ́ aláìṣọ̀kan, aláìhàn, àti aláìṣiṣẹ́ dáadáa",
    "ps.p1": "Àwọn MSME ní ìṣòro láti rí owó àwín nítorí àìní ìmọ̀ tó dára nípa owó tí ó ń wọlé àti tí ó ń jáde",
    "ps.p2": "Àwọn aláwín kò ní àmì ewu tó gbẹ́kẹ̀lé fún àwọn iṣẹ́ aláìṣètò",
    "ps.p3": "Àwọn àǹfààní ẹ̀bùn jẹ́ aláìṣọ̀kan àti pé ó ṣòro láti rí",
    "ps.p4": "Àwọn olùṣe ìlànà kò ní dátà MSME tó péye fún ìgbèrò",
    "ps.solutionTag": "Ojútùú Náà",
    "ps.solutionTitle": "Bailout: Ọjà ìṣúná oníjù méjì",
    "ps.solutionDesc": 'Tí ó ń ṣiṣẹ́ pẹ̀lú ẹ̀rọ ìmọ̀ kírẹ́dìtì, tí ó ń ṣiṣẹ́ bíi "Bánkì-nínú-Àpótí" — tó ṣeé yàn, tó dá lórí dátà, àti tó ṣeé ṣọ̀kan.',
    "ps.s1": "Bá àwọn aláìní owó mu pẹ̀lú ohun èlò àwín tó bá wọn mu",
    "ps.s2": "So àwọn tí ó ń wá ẹ̀bùn pọ̀ mọ́ àǹfààní tó bá wọn mu",
    "ps.s3": "Ṣàyẹ̀wò ewu nípa lílo dátà iṣòwò + àwọn ìgbéwọlé owó àfọwọ́ṣe",
    "ps.s4": "Pèsè ìtúpalẹ̀ ọjà aláìdámọ̀ fún àwọn àjọ",
    "ps.ctaTitle": "Ṣé o ti ṣetán láti yí iṣẹ́ rẹ padà?",
    "ps.ctaDesc": "Darapọ̀ mọ́ ẹgbẹẹgbẹ̀rún àwọn MSME tí wọ́n ti ń lo Bailout láti rí owó.",
    "ps.ctaButton": "Bẹ̀rẹ̀ Lónìí",

    "features.tag": "Àwọn Ẹ̀yà Pàtàkì",
    "features.title1": "Gbogbo ohun tí o nílò láti",
    "features.titleHighlight": "rí owó",
    "features.subtitle": "Pẹpẹ wa tó pé pèsè gbogbo irinṣẹ́ tí àwọn MSME nílò láti so pọ̀ mọ́ àwọn aláwín àti rí ẹ̀bùn.",
    "features.f1Title": "Àkọọ́lẹ̀ Oníbàárà",
    "features.f1Desc": "Àkọọ́lẹ̀ iṣẹ́ tó sopọ̀ mọ́ CAC pẹ̀lú àlàyé ẹ̀ka, àsopọ̀ POS, ìtọpinpin iṣòwò, àti ìtàn kírẹ́dìtì.",
    "features.f2Title": "Ìbámu Aláwín-Aláìní",
    "features.f2Desc": "Algoridimu tó dá lórí ìlànà + ìṣirò tí ó ń wo ìdúróṣinṣin owó wíwọlé, ìtẹ̀síwájú owó owó, àti ewu ẹ̀ka.",
    "features.f3Title": "Ẹ̀rọ Ìwárí Ẹ̀bùn",
    "features.f3Desc": "Rí àwọn ẹ̀bùn tó bá àkọọ́lẹ̀ iṣẹ́ rẹ, ẹ̀ka, àti àwọn ìbéèrè mu.",
    "features.f4Title": "Ìṣirò Kírẹ́dìtì & Ewu",
    "features.f4Desc": "Àwòṣe àdàpọ̀ tó ń lo àwọn ìwọ̀n tó dá lórí iṣòwò àti àwọn àfihàn ìwà iṣẹ́.",
    "features.f5Title": "Ìpínfúnni Aláàbò",
    "features.f5Desc": "Gbígba ipèsè, ìtọpinpin ìpínfúnni, àti ìṣàyẹ̀wò ipò ìsanpadà.",
    "features.f6Title": "Ìmọ̀ Ọjà",
    "features.f6Desc": "Àwọn ìmọ̀ àpapọ̀ lórí àwọn ìtẹ̀síwájú ẹ̀ka, ìbéèrè kírẹ́dìtì, àti àwọn àfihàn àgbègbè.",

    "vp.tag": "Àwọn Ànfààní",
    "vp.title1": "Àǹfààní fún",
    "vp.titleHighlight": "gbogbo ènìyàn",
    "vp.borrowerTag": "Fún Àwọn Aláìní / MSME",
    "vp.borrowerTitle": "Ṣí àǹfààní iṣẹ́ rẹ sílẹ̀",
    "vp.b1Title": "Ṣí Àǹfààní",
    "vp.b1Desc": "Ṣàwárí àwọn àṣàyàn ìṣúná àti ìmọ̀ràn tó bá àìní iṣẹ́ rẹ mu.",
    "vp.b2Title": "Ohun Elo Lásán",
    "vp.b2Desc": "Ṣe ohun elo lọ́nà ìrọ̀rùn nípa pẹpẹ dígítà wa.",
    "vp.b3Title": "Ìmúdójúìwọ̀n Lásìkò",
    "vp.b3Desc": "Gbọ́ nípa gbogbo ìgbésẹ̀ nínú ìrìn-àjò ohun elo rẹ.",
    "vp.lenderTag": "Fún Àwọn Aláwín / Àjọ",
    "vp.lenderTitle": "Ṣe ìpinnu àwín tó gbọ́n jù",
    "vp.l1Title": "Ewu Kékeré",
    "vp.l1Desc": "Ìmọ̀ tó dá lórí dátà dín ewu àwín kù gidigidi.",
    "vp.l2Title": "Ìṣàkóso Tó Dára",
    "vp.l2Desc": "Àǹfààní sí àwọn aláìní MSME tó ti jẹ́ àyẹ̀wò.",
    "vp.l3Title": "Ìmọ̀ Ọjà",
    "vp.l3Desc": "Ìgbèrò ọgbọ́n pẹ̀lú ìmọ̀ ọjà tó pé.",

    "mv.missionTitle": "Iṣẹ́ Àyànfúnni Wa",
    "mv.missionDesc": "Láti mú ànfààní ìṣúná rọrùn nípa ṣíṣe àjọpọ̀ àwọn iṣẹ́, àwọn aláwín, àti àwọn olùpèsè ẹ̀bùn lórí pẹpẹ kan tó hàn gbangba.",
    "mv.visionTitle": "Ìran Wa",
    "mv.visionDesc": "Láti di pẹpẹ tí àwọn ènìyàn gbẹ́kẹ̀lé jù lọ ní Áfíríkà fún ìdàgbàsókè ìṣúná tó ṣàkópọ̀ àti ìmúlágbára MSME.",
    "mv.longTermTitle": "Ìran Ìgbà Pípẹ́",
    "mv.lt1": "Ètò ìṣiṣẹ́ ìṣúná MSME ti Nàìjíríà",
    "mv.lt2": "Àfàrà láàrín owó aláìṣètò àti kírẹ́dìtì aláṣètò",
    "mv.lt3": "Ìpele dátà tó gbẹ́kẹ̀lé fún ìṣúná tó ṣàkópọ̀",

    "team.tag": "Ẹgbẹ́ Wa",
    "team.title1": "Pàdé àwọn",
    "team.titleHighlight": "olùdásílẹ̀",
    "team.subtitle": "Ẹgbẹ́ àwọn ọjọ́gbọ́n tó yàn ara wọn sí fún ìyípadà ànfààní ìṣúná MSME ní Nàìjíríà.",
    "team.jmRole": "Olùdásílẹ̀",
    "team.jmDesc": "Ọjọ́gbọ́n iṣẹ́ ìṣúná pẹ̀lú ìmọ̀ nínú ìṣàkóso ewu, ìlànà, àti àwọn ètò àwín.",
    "team.iaRole": "Alábàáṣiṣẹ́pọ̀ Olùdásílẹ̀",
    "team.iaDesc": "Mú ìmọ̀ wá nínú ìlànà, ìṣiṣẹ́, àti ìkọ́ ẹgbẹ́; ń mú ìṣọ̀kan àti ìdàgbàsókè àjọ.",
    "team.soRole": "Alábàáṣiṣẹ́pọ̀ Ọgbọ́n & Olùdásílẹ̀",
    "team.soDesc": "Olùmọ̀ràn pẹ̀lú ìrírí tó lágbára nínú àtìlẹ́yìn iṣẹ́-ọwọ́, àwọn ìlànà ìṣúná, àti ìdàgbàsókè SME.",
    "team.amRole": "Alábàáṣiṣẹ́pọ̀ Olùdásílẹ̀",
    "team.amDesc": "Ṣe ipa pàtàkì nínú dídá èrò Bailout, tí ó ń ṣe ìwádìí, ìlànà, àti ìṣiṣẹ́ àpẹẹrẹ.",

    "footer.desc": "Ṣíṣe àjọpọ̀ àwọn MSME pẹ̀lú àwín, ẹ̀bùn, àti àwọn àjọ ìṣúná lọ́nà títọ́, tó dá lórí dátà, tó dojúkọ Nàìjíríà.",
    "footer.quickLinks": "Àwọn Àjọpọ̀ Kíákíá",
    "footer.aboutUs": "Nípa Wa",
    "footer.solution": "Ojútùú",
    "footer.features": "Àwọn Ẹ̀yà",
    "footer.ourTeam": "Ẹgbẹ́ Wa",
    "footer.forUsers": "Fún Àwọn Oníbàárà",
    "footer.borrowers": "Àwọn MSME / Aláìní",
    "footer.lenders": "Àwọn Aláwín",
    "footer.grantProviders": "Àwọn Olùpèsè Ẹ̀bùn",
    "footer.institutions": "Àwọn Àjọ",
    "footer.contactUs": "Kàn Sí Wa",
    "footer.copyright": "© 2026 Prime-Up Solutions Ltd. Gbogbo ẹ̀tọ́ wà ní ìpamọ́.",
    "footer.privacy": "Ìlànà Àṣírí",
    "footer.terms": "Àwọn Òfin Iṣẹ́",
  },

  ha: {
    "nav.about": "Game Mu",
    "nav.solution": "Mafita",
    "nav.features": "Fasaloli",
    "nav.team": "Ƙungiya",
    "nav.help": "Taimako",
    "nav.getStarted": "Fara",

    "hero.badge": "Dandalin Kuɗi na MSME na Nijeriya",
    "hero.title1": "Haɗa MSME zuwa",
    "hero.titleHighlight": "Bashi, Tallafi",
    "hero.title2": "& Haɓaka Kuɗi",
    "hero.subtitle": "Haɗa kasuwanci zuwa damar samun kuɗi ta hanyar gaskiya tare da bayanai masu ma'ana. An gina don Nijeriya, an tsara don haɓaka.",
    "hero.cta1": "Fara Neman Ka",
    "hero.cta2": "Ƙara Koyo",
    "hero.stat1Value": "₦50B+",
    "hero.stat1Label": "Damar Kuɗi",
    "hero.stat2Value": "10K+",
    "hero.stat2Label": "MSME da aka Haɗa",
    "hero.stat3Value": "100+",
    "hero.stat3Label": "Cibiyoyin Abokan Hulɗa",

    "whatwedo.tag": "Abin da Muke Yi",
    "whatwedo.title1": "Ƙarfafa MSME don",
    "whatwedo.titleHighlight": "Ci Gaba Mai Ɗorewa",
    "whatwedo.subtitle": "A Prime-Up Solutions (Bailout), muna ƙarfafa Ƙanana, Matsakaita da Manyan Kasuwanci ta hanyar inganta samun kuɗi, bayar da shawarwari na ƙwararru, da haɗa kasuwanci zuwa damammaki masu kyau.",
    "whatwedo.f1Title": "Tallafin Kuɗin MSME",
    "whatwedo.f1Desc": "Haɗa kasuwanci zuwa damar samun kuɗi da ya dace da buƙatunsu.",
    "whatwedo.f2Title": "Shawarwarin Kuɗi",
    "whatwedo.f2Desc": "Jagora ta ƙwararru kan sarrafa kuɗi, dabarun haɓaka, da ci gaba mai ɗorewa.",
    "whatwedo.f3Title": "Hanzarta Haɓaka",
    "whatwedo.f3Desc": "Tallafa wa faɗaɗawa ta hanyar ayyuka masu tsari da tsare-tsare na dabara.",
    "whatwedo.f4Title": "Sabbin Hanyoyi & Kayan Aiki",
    "whatwedo.f4Desc": "Hanyoyin kuɗi masu tushe a bayanai waɗanda ke taimaka wa kasuwanci yanke shawara masu kyau.",

    "ps.problemTag": "Matsalar",
    "ps.problemTitle": "Tsarin yanzu ba su da haɗin kai, ba a iya gani, kuma ba su da inganci",
    "ps.p1": "MSME suna fuskantar wahalar samun bashi saboda rashin ganin kuɗin da ke shiga da fita",
    "ps.p2": "Masu ba da bashi ba su da alamun haɗari masu aminci ga kasuwancin da ba na tsari ba",
    "ps.p3": "Damar tallafi sun watse kuma suna da wuya a same su",
    "ps.p4": "Masu tsara manufofi ba su da cikakken bayanan MSME don tsarawa",
    "ps.solutionTag": "Mafita",
    "ps.solutionTitle": "Bailout: Kasuwar kuɗi mai fuskoki biyu",
    "ps.solutionDesc": "Tana aiki da injin binciken bashi, tana aiki kamar \"Banki-a-cikin-Akwati\" — mai sassauƙa, mai tushe a bayanai, kuma mai haɗin kai.",
    "ps.s1": "Daidaita masu neman bashi zuwa kayan aiki masu dacewa",
    "ps.s2": "Haɗa masu neman tallafi zuwa damammaki masu dacewa",
    "ps.s3": "Tantance haɗari ta amfani da bayanan ciniki + shigar kuɗi na hannu",
    "ps.s4": "Bayar da nazarin kasuwa marar suna ga cibiyoyi",
    "ps.ctaTitle": "Shin ka shirya don canza kasuwancinka?",
    "ps.ctaDesc": "Ka haɗa da dubun-dubatar MSME da suke amfani da Bailout don samun kuɗi.",
    "ps.ctaButton": "Fara Yau",

    "features.tag": "Manyan Fasaloli",
    "features.title1": "Duk abin da kake buƙata don",
    "features.titleHighlight": "samun kuɗi",
    "features.subtitle": "Dandamalinmu mai cikakken bayani yana bayar da duk kayan aikin da MSME ke buƙata don haɗawa da masu ba da bashi da samun tallafi.",
    "features.f1Title": "Bayanan Masu Amfani",
    "features.f1Desc": "Bayanan kasuwanci da ke haɗe da CAC tare da cikakken bayanin ɓangare, haɗin POS, bin diddigin ciniki, da tarihin bashi.",
    "features.f2Title": "Daidaita Mai Ba Bashi da Mai Nema",
    "features.f2Desc": "Algorithm mai tushe a ƙa'idoji + maki wanda ke la'akari da kwanciyar kuɗin shiga, yanayin samun kuɗi, da haɗarin ɓangare.",
    "features.f3Title": "Injin Gano Tallafi",
    "features.f3Desc": "Nemo tallafin da ya dace bisa bayanan kasuwancinka, ɓangare, da ƙa'idojin cancanta.",
    "features.f4Title": "Maki Bashi & Haɗari",
    "features.f4Desc": "Tsarin cakuɗe mai amfani da ma'aunin ciniki da alamun halayen kasuwanci.",
    "features.f5Title": "Rarraba Mai Tsaro",
    "features.f5Desc": "Karɓar tayin, bin diddigin rarrabawa, da sa ido kan yanayin biya.",
    "features.f6Title": "Bayanan Kasuwa",
    "features.f6Desc": "Haɗaɗɗun bayanai kan yanayin ɓangare, buƙatun bashi, da alamun yanki.",

    "vp.tag": "Fa'idodi",
    "vp.title1": "Fa'idodi ga",
    "vp.titleHighlight": "kowa",
    "vp.borrowerTag": "Ga Masu Neman Bashi / MSME",
    "vp.borrowerTitle": "Buɗe yuwuwar kasuwancinka",
    "vp.b1Title": "Buɗe Damammaki",
    "vp.b1Desc": "Gano damar kuɗi da shawarwari da suka dace da buƙatun kasuwancinka.",
    "vp.b2Title": "Nema Mara Wahala",
    "vp.b2Desc": "Yi nema cikin sauƙi ta dandamalinmu na dijital.",
    "vp.b3Title": "Sabuntawa Na Lokaci-Lokaci",
    "vp.b3Desc": "Ka kasance cikin sani a kowane mataki na tafiyar nemanka.",
    "vp.lenderTag": "Ga Masu Ba Da Bashi / Cibiyoyi",
    "vp.lenderTitle": "Yi shawarar ba da bashi mai hikima",
    "vp.l1Title": "Ƙarancin Haɗari",
    "vp.l1Desc": "Bayanai masu tushe a data suna rage haɗarin ba da bashi sosai.",
    "vp.l2Title": "Layukan da aka Tantance",
    "vp.l2Desc": "Samun damar MSME masu neman bashi da aka riga aka tantance.",
    "vp.l3Title": "Bayanan Kasuwa",
    "vp.l3Desc": "Tsare-tsare na dabara tare da cikakkun bayanan kasuwa.",

    "mv.missionTitle": "Manufarmu",
    "mv.missionDesc": "Don sauƙaƙe samun kuɗi ta hanyar haɗa kasuwanci, masu ba da bashi, da masu bayar da tallafi a kan dandamali ɗaya mai gaskiya.",
    "mv.visionTitle": "Hangen Nesanmu",
    "mv.visionDesc": "Don zama dandamali mafi aminci a Afirka don haɓaka kuɗi mai haɗa kowa da ƙarfafa MSME.",
    "mv.longTermTitle": "Hangen Nesa Na Dogon Lokaci",
    "mv.lt1": "Tsarin kuɗin MSME na Nijeriya",
    "mv.lt2": "Gadar dake tsakanin kuɗin da ba na tsari ba da bashi na tsari",
    "mv.lt3": "Matakin bayanai mai aminci don kuɗi mai haɗa kowa",

    "team.tag": "Ƙungiyarmu",
    "team.title1": "Haɗu da",
    "team.titleHighlight": "masu kafa",
    "team.subtitle": "Ƙungiyar ƙwararru da suka sadaukar da kansu don canza samun kuɗin MSME a Nijeriya.",
    "team.jmRole": "Mai Kafa",
    "team.jmDesc": "Ƙwararren sabis na kuɗi mai ƙwarewa a sarrafa haɗari, dabara, da tsarin bashi.",
    "team.iaRole": "Abokin Kafa",
    "team.iaDesc": "Yana kawo ƙwarewa a dabara, ayyuka, da gina ƙungiya; yana tafiyar da daidaituwa da haɓaka ƙungiya.",
    "team.soRole": "Abokin Dabara & Abokin Kafa",
    "team.soDesc": "Mai shawara mai gogewa sosai a tallafin kasuwanci, dabarun kuɗi, da haɓaka SME.",
    "team.amRole": "Abokin Kafa",
    "team.amDesc": "Yana da muhimmanci wajen tsara ra'ayin Bailout, yana jagorantar bincike, dabara, da aiwatar da ƙira.",

    "footer.desc": "Haɗa MSME zuwa bashi, tallafi, da cibiyoyin kuɗi cikin gaskiya, mai tushe a bayanai, mai mayar da hankali ga Nijeriya.",
    "footer.quickLinks": "Hanyoyin Sauri",
    "footer.aboutUs": "Game Mu",
    "footer.solution": "Mafita",
    "footer.features": "Fasaloli",
    "footer.ourTeam": "Ƙungiyarmu",
    "footer.forUsers": "Ga Masu Amfani",
    "footer.borrowers": "MSME / Masu Neman Bashi",
    "footer.lenders": "Masu Ba Da Bashi",
    "footer.grantProviders": "Masu Bayar da Tallafi",
    "footer.institutions": "Cibiyoyi",
    "footer.contactUs": "Tuntuɓe Mu",
    "footer.copyright": "© 2026 Prime-Up Solutions Ltd. An kiyaye duk haƙƙoƙi.",
    "footer.privacy": "Manufar Sirri",
    "footer.terms": "Sharuɗɗan Sabis",
  },

  ig: {
    "nav.about": "Maka Anyị",
    "nav.solution": "Ihe Ngwọta",
    "nav.features": "Njirimara",
    "nav.team": "Ndị Otu",
    "nav.help": "Enyemaka",
    "nav.getStarted": "Bido",

    "hero.badge": "Ikpo Okwu Ego MSME nke Naịjirịa",
    "hero.title1": "Ijikọ MSME na",
    "hero.titleHighlight": "Mgbazinye, Onyinye",
    "hero.title2": "& Ọganihu Ego",
    "hero.subtitle": "Ijikọ azụmaahịa na ohere ego n'ụzọ doro anya site na nghọta dabere na data. Ewuru maka Naịjirịa, emere maka ọganihu.",
    "hero.cta1": "Bido Arịrịọ Gị",
    "hero.cta2": "Mụtakwuo",
    "hero.stat1Value": "₦50B+",
    "hero.stat1Label": "Ohere Ego",
    "hero.stat2Value": "10K+",
    "hero.stat2Label": "MSME Ejikọrọ",
    "hero.stat3Value": "100+",
    "hero.stat3Label": "Ụlọ Ọrụ Ndị Mmekọ",

    "whatwedo.tag": "Ihe Anyị Na-eme",
    "whatwedo.title1": "Ịme ka MSME sie ike maka",
    "whatwedo.titleHighlight": "Ọganihu Na-adịgide",
    "whatwedo.subtitle": "Na Prime-Up Solutions (Bailout), anyị na-eme ka azụmaahịa obere, nke etiti na nke buru ibu sie ike site n'ịmụbata ohere ego, inye ndụmọdụ ọkachamara, na ijikọ azụmaahịa na ohere ndị kwesịrị ekwesị.",
    "whatwedo.f1Title": "Nkwado Ego MSME",
    "whatwedo.f1Desc": "Ijikọ azụmaahịa na ohere ego nke kwesịrị mkpa ha na ikike ha.",
    "whatwedo.f2Title": "Ndụmọdụ Ego",
    "whatwedo.f2Desc": "Nduzi ọkachamara banyere njikwa ego, atụmatụ ọganihu, na ịrụ ọrụ na-adịgide.",
    "whatwedo.f3Title": "Ịme Ka Ọganihu Dị Ọsọ",
    "whatwedo.f3Desc": "Ịkwado mwụba site na ọrụ nwere usoro na atụmatụ nke lekwasịrị anya.",
    "whatwedo.f4Title": "Ihe Ọhụrụ & Ngwá Ọrụ",
    "whatwedo.f4Desc": "Ihe ngwọta ego dabere na data nke na-enyere azụmaahịa aka ịkpebisie mkpebi ọma.",

    "ps.problemTag": "Nsogbu A",
    "ps.problemTitle": "Usoro ugbu a ekesaghị, a dịghị ahụ anya, ọ dịghịkwa arụ ọrụ nke ọma",
    "ps.p1": "MSME na-enwe nsogbu ịnweta kredit n'ihi enweghị ike ịhụ ego na-abata na nke na-apụ",
    "ps.p2": "Ndị na-agbazinye ego enweghị akara ihe egwu ndị a pụrụ ịdabere na ha maka azụmaahịa na-enweghị usoro",
    "ps.p3": "Ohere onyinye gbasasịrị ma siri ike ịchọta",
    "ps.p4": "Ndị na-eme iwu enweghị data MSME zuru oke maka ịhazi",
    "ps.solutionTag": "Ihe Ngwọta",
    "ps.solutionTitle": "Bailout: Ahịa ego nwere akụkụ abụọ",
    "ps.solutionDesc": "Nke njigide kredit na-akwụ ụgwọ, na-arụ ọrụ dịka \"Ụlọ Akụ-nọ-n'Igbe\" — nke a pụrụ ịhọrọ, dabere na data, na nke na-arụkọ ọrụ.",
    "ps.s1": "Dakọtara ndị chọrọ ego na ngwá ọrụ mgbazinye kwesịrị ekwesị",
    "ps.s2": "Jikọọ ndị na-achọ onyinye na ohere kwesịrị ekwesị",
    "ps.s3": "Tụlee ihe egwu site n'iji data azụmahịa + ntinye ego nke aka",
    "ps.s4": "Na-enye nyocha ahịa na-anapụtaghị aha maka ụlọ ọrụ",
    "ps.ctaTitle": "Ị dị njikere ịgbanwe azụmaahịa gị?",
    "ps.ctaDesc": "Sonyere ọtụtụ puku MSME ndị na-eji Bailout enweta ego ugbu a.",
    "ps.ctaButton": "Bido Taa",

    "features.tag": "Njirimara Bụ Isi",
    "features.title1": "Ihe niile ị chọrọ iji",
    "features.titleHighlight": "nweta ego",
    "features.subtitle": "Ikpo okwu anyị zuru oke na-enye ngwá ọrụ niile MSME chọrọ iji jikọọ na ndị na-agbazinye ego ma nweta onyinye.",
    "features.f1Title": "Profaịlụ Ndị Ọrụ",
    "features.f1Desc": "Profaịlụ azụmaahịa ejikọtara na CAC nwere nkọwa ngalaba, njikọ POS, ịsọ azụmahịa, na akụkọ kredit.",
    "features.f2Title": "Ndakọta Onye Na-agbazinye na Onye Na-achọ",
    "features.f2Desc": "Algọridim dabere na iwu + akara nke na-atụle ndịda ego, mmụba ego, na ihe egwu ngalaba.",
    "features.f3Title": "Injin Ịchọta Onyinye",
    "features.f3Desc": "Chọta onyinye kwesịrị ekwesị dabere na profaịlụ azụmaahịa gị, ngalaba, na usoro iru uru.",
    "features.f4Title": "Akara Kredit & Ihe Egwu",
    "features.f4Desc": "Ụdị agwakọta nke na-eji metrik dabere na azụmahịa na ihe ngosi omume azụmaahịa.",
    "features.f5Title": "Nkesa Nchekwa",
    "features.f5Desc": "Nnabata onyinye, ịsọ nkesa, na nleba anya ọnọdụ nkwụghachi.",
    "features.f6Title": "Ọgụgụ Isi Ahịa",
    "features.f6Desc": "Nghọta agbakọtara banyere ọdịda ngalaba, mkpa kredit, na ihe ngosi mpaghara.",

    "vp.tag": "Uru Ndị A",
    "vp.title1": "Uru maka",
    "vp.titleHighlight": "onye ọ bụla",
    "vp.borrowerTag": "Maka Ndị Na-agbaziri / MSME",
    "vp.borrowerTitle": "Meghere ikike azụmaahịa gị",
    "vp.b1Title": "Meghere Ohere",
    "vp.b1Desc": "Chọpụta ohere ego na ndụmọdụ kwesịrị mkpa azụmaahịa gị.",
    "vp.b2Title": "Arịrịọ Dị Mfe",
    "vp.b2Desc": "Tinye arịrịọ n'ụzọ dị mfe site na ikpo okwu dijitalụ anyị.",
    "vp.b3Title": "Mmelite N'oge Ezigbo",
    "vp.b3Desc": "Nọgidenụ n'ịma ama n'oge niile nke njem arịrịọ gị.",
    "vp.lenderTag": "Maka Ndị Na-agbazinye / Ụlọ Ọrụ",
    "vp.lenderTitle": "Mee mkpebi igbazinye ego nke ọma",
    "vp.l1Title": "Ihe Egwu Dị Ntakịrị",
    "vp.l1Desc": "Nghọta dabere na data na-ebelata ihe egwu igbazinye ego nke ukwuu.",
    "vp.l2Title": "Ahịrị Ndị A Nyochara",
    "vp.l2Desc": "Ịnweta ndị MSME a nyochara ma kwado.",
    "vp.l3Title": "Ọgụgụ Isi Ahịa",
    "vp.l3Desc": "Atụmatụ nke lekwasịrị anya na nghọta ahịa zuru oke.",

    "mv.missionTitle": "Ọrụ Anyị",
    "mv.missionDesc": "Ịme ka ịnweta ego dịrị mfe site n'ijikọ azụmaahịa, ndị na-agbazinye ego, na ndị na-enye onyinye n'otu ikpo okwu doro anya.",
    "mv.visionTitle": "Ọhụụ Anyị",
    "mv.visionDesc": "Ịbụ ikpo okwu a tụkwasịrị obi karịsịa na Afrịka maka ọganihu ego nke gụnyere mmadụ niile na ịme ka MSME sie ike.",
    "mv.longTermTitle": "Ọhụụ Ogologo Oge",
    "mv.lt1": "Usoro ego MSME nke Naịjirịa",
    "mv.lt2": "Àkwà mmiri n'etiti ego na-enweghị usoro na kredit nwere usoro",
    "mv.lt3": "Ọkwa data a tụkwasịrị obi maka ego nke gụnyere mmadụ niile",

    "team.tag": "Ndị Otu Anyị",
    "team.title1": "Zute ndị",
    "team.titleHighlight": "hiwere ya",
    "team.subtitle": "Otu ndị ọkachamara raara onwe ha nye maka ịgbanwe ohere ego MSME na Naịjirịa.",
    "team.jmRole": "Onye Hiwere",
    "team.jmDesc": "Ọkachamara ọrụ ego nwere nkà na ịchịkwa ihe egwu, atụmatụ, na usoro mgbazinye.",
    "team.iaRole": "Onye Mmekọ Hiwere",
    "team.iaDesc": "Na-eweta nkà na atụmatụ, ọrụ, na ịwu otu; na-akwụ ụgwọ nhazi na ọganihu ụlọ ọrụ.",
    "team.soRole": "Onye Mmekọ Atụmatụ & Onye Hiwere",
    "team.soDesc": "Onye ndụmọdụ nwere ahụmịhe siri ike na nkwado azụmaahịa, atụmatụ ego, na mmepe SME.",
    "team.amRole": "Onye Mmekọ Hiwere",
    "team.amDesc": "Dị mkpa n'ịhazi echiche Bailout, na-akwụ ụgwọ nyocha, atụmatụ, na mmejupụta nhazi.",

    "footer.desc": "Ijikọ MSME na mgbazinye, onyinye, na ụlọ ọrụ ego n'ụzọ doro anya, dabere na data, lekwasịrị anya na Naịjirịa.",
    "footer.quickLinks": "Njikọ Ngwa Ngwa",
    "footer.aboutUs": "Maka Anyị",
    "footer.solution": "Ihe Ngwọta",
    "footer.features": "Njirimara",
    "footer.ourTeam": "Ndị Otu Anyị",
    "footer.forUsers": "Maka Ndị Ọrụ",
    "footer.borrowers": "MSME / Ndị Na-agbaziri",
    "footer.lenders": "Ndị Na-agbazinye",
    "footer.grantProviders": "Ndị Na-enye Onyinye",
    "footer.institutions": "Ụlọ Ọrụ",
    "footer.contactUs": "Kpọtụrụ Anyị",
    "footer.copyright": "© 2026 Prime-Up Solutions Ltd. Ikike niile echekwara.",
    "footer.privacy": "Iwu Nzuzo",
    "footer.terms": "Usoro Ọrụ",
  },

  pcm: {
    "nav.about": "About Us",
    "nav.solution": "Solution",
    "nav.features": "Features",
    "nav.team": "Team",
    "nav.help": "Help",
    "nav.getStarted": "Start Now",

    "hero.badge": "Naija MSME Money Platform",
    "hero.title1": "Connecting Small Business to",
    "hero.titleHighlight": "Loan, Grant",
    "hero.title2": "& Money Growth",
    "hero.subtitle": "We dey connect business people to money opportunity with correct data. We build am for Naija, we design am for growth.",
    "hero.cta1": "Start Your Application",
    "hero.cta2": "Learn More",
    "hero.stat1Value": "₦50B+",
    "hero.stat1Label": "Money Opportunity",
    "hero.stat2Value": "10K+",
    "hero.stat2Label": "Small Business Wey Connect",
    "hero.stat3Value": "100+",
    "hero.stat3Label": "Partner Company",

    "whatwedo.tag": "Wetin We Dey Do",
    "whatwedo.title1": "We Dey Strengthen Small Business for",
    "whatwedo.titleHighlight": "Better Growth",
    "whatwedo.subtitle": "For Prime-Up Solutions (Bailout), we dey help Small and Medium Business by making sure say dem fit get money, we give expert advice, and we connect dem to the right opportunity.",
    "whatwedo.f1Title": "Small Business Money Support",
    "whatwedo.f1Desc": "We dey connect business to the right money opportunity wey fit their need.",
    "whatwedo.f2Title": "Money Advice",
    "whatwedo.f2Desc": "Expert guide on how to manage cash, grow well, and keep your business running.",
    "whatwedo.f3Title": "Fast Growth Support",
    "whatwedo.f3Desc": "We dey support expansion through proper planning and structured operations.",
    "whatwedo.f4Title": "New Ideas & Tools",
    "whatwedo.f4Desc": "Data-based money solutions wey help business make better decisions.",

    "ps.problemTag": "The Problem",
    "ps.problemTitle": "The current system no dey work well at all",
    "ps.p1": "Small business dey struggle to get loan because nobody fit see their cashflow well",
    "ps.p2": "People wey dey give loan no get correct info about informal business risk",
    "ps.p3": "Grant opportunity scatter everywhere and hard to find",
    "ps.p4": "Government people no get correct small business data to plan with",
    "ps.solutionTag": "The Solution",
    "ps.solutionTitle": "Bailout: Two-sided money marketplace",
    "ps.solutionDesc": "E dey powered by credit intelligence engine, e dey work like \"Bank-for-Pocket\" — flexible, data-driven, and e fit work with anything.",
    "ps.s1": "We dey match people wey need loan to the right loan product",
    "ps.s2": "We dey connect grant seekers to the right opportunity",
    "ps.s3": "We dey check risk using transaction data plus manual cash input",
    "ps.s4": "We dey give anonymous market data to big organizations",
    "ps.ctaTitle": "You ready to change your business?",
    "ps.ctaDesc": "Join thousands of small business wey already dey use Bailout to get money.",
    "ps.ctaButton": "Start Today",

    "features.tag": "Main Features",
    "features.title1": "Everything you need to",
    "features.titleHighlight": "get funding",
    "features.subtitle": "Our platform get all the tools wey small business need to connect with people wey go give dem money and grant.",
    "features.f1Title": "User Profiles",
    "features.f1Desc": "Business profile wey link to CAC with sector info, POS connection, transaction tracking, and credit history.",
    "features.f2Title": "Lender-Borrower Matching",
    "features.f2Desc": "Smart algorithm wey dey consider cashflow, revenue trend, and sector risk to match you.",
    "features.f3Title": "Grant Finder",
    "features.f3Desc": "Find grants wey match your business profile, sector, and eligibility.",
    "features.f4Title": "Credit Score & Risk",
    "features.f4Desc": "Mix model wey use transaction data and business behavior to score you.",
    "features.f5Title": "Safe Money Transfer",
    "features.f5Desc": "Accept offer, track money wey dem send, and monitor repayment status.",
    "features.f6Title": "Market Info",
    "features.f6Desc": "Combined insights about sector trends, credit demand, and area indicators.",

    "vp.tag": "Why E Good",
    "vp.title1": "Benefits for",
    "vp.titleHighlight": "everybody",
    "vp.borrowerTag": "For People Wey Need Money / Small Business",
    "vp.borrowerTitle": "Unlock wetin your business fit do",
    "vp.b1Title": "Open Doors",
    "vp.b1Desc": "Find money and advice options wey fit your business need.",
    "vp.b2Title": "Easy Application",
    "vp.b2Desc": "Apply easily through our digital platform.",
    "vp.b3Title": "Real-Time Updates",
    "vp.b3Desc": "Know wetin dey happen every step of your application.",
    "vp.lenderTag": "For People Wey Give Loan / Big Company",
    "vp.lenderTitle": "Make smarter lending decisions",
    "vp.l1Title": "Less Risk",
    "vp.l1Desc": "Data-based insights reduce lending risk well well.",
    "vp.l2Title": "Checked Pipeline",
    "vp.l2Desc": "Access to small business borrowers wey don already pass screening.",
    "vp.l3Title": "Market Info",
    "vp.l3Desc": "Plan well with complete market insights.",

    "mv.missionTitle": "Our Mission",
    "mv.missionDesc": "To make am easy to get money by connecting business, lenders, and grant providers for one transparent platform.",
    "mv.visionTitle": "Our Vision",
    "mv.visionDesc": "To become the most trusted platform for Africa for inclusive money growth and small business empowerment.",
    "mv.longTermTitle": "Long-term Vision",
    "mv.lt1": "Naija MSME financial operating system",
    "mv.lt2": "Bridge between informal cashflow and formal credit",
    "mv.lt3": "Trusted data layer for money wey include everybody",

    "team.tag": "Our Team",
    "team.title1": "Meet the",
    "team.titleHighlight": "founders",
    "team.subtitle": "Dedicated team of professionals wey dey committed to changing how small business get money for Naija.",
    "team.jmRole": "Founder",
    "team.jmDesc": "Money services professional with experience for risk management, strategy, and loan systems.",
    "team.iaRole": "Co-Founder",
    "team.iaDesc": "E bring expertise for strategy, operations, and team-building; e dey drive alignment and growth.",
    "team.soRole": "Strategic Partner & Co-Founder",
    "team.soDesc": "Advisor with strong experience for business support, funding strategies, and SME development.",
    "team.amRole": "Co-Founder",
    "team.amDesc": "E help shape the Bailout concept, driving research, strategy, and design execution.",

    "footer.desc": "Connecting small business to loan, grant, and money institutions — transparent, data-driven, Naija-focused.",
    "footer.quickLinks": "Quick Links",
    "footer.aboutUs": "About Us",
    "footer.solution": "Solution",
    "footer.features": "Features",
    "footer.ourTeam": "Our Team",
    "footer.forUsers": "For Users",
    "footer.borrowers": "Small Business / Borrowers",
    "footer.lenders": "Lenders",
    "footer.grantProviders": "Grant Providers",
    "footer.institutions": "Institutions",
    "footer.contactUs": "Contact Us",
    "footer.copyright": "© 2026 Prime-Up Solutions Ltd. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
  },
};
